name: CI/CD

on:
  push:
    paths:
      - src/**
      - .github/workflows/ci-cd.yml
      - package.json
      - package-lock.json
  pull_request:

jobs:
  build:
    name: Build Dispatch
    if: ${{ !contains(github.event.head_commit.message, '[failing]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build routes
        run: npm run build:tsoa
        env:
          NODE_ENV: production

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Upload built project
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: build/*
